In [1]:
mysql://root:ifsp@localhost

In [2]:
SHOW databases;

,Database
0,information_schema
1,mysql
2,performance_schema
3,sakila
4,sys
5,teste
6,world

In [3]:
CREATE DATABASE aula07;

In [4]:
USE aula07

In [6]:
CREATE TABLE aluno (
    id_aluno INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50),
    idade INT,
    nota FLOAT
);

In [13]:
INSERT INTO aluno (nome, idade, nota) VALUES
('Alice', 20, 8.5),
('Bob', 18, 7.4),
('Charlie', 22, 9.1),
('Diana', 17, 5.5),
('Edward', 21, 7.7),
('Fiona', 19, 9.9),
('George', 20, 9.8),
('Hannah', 19, 9.4),
('Ian', 21, 5.7),
('Julia', 18, 9.2),
('Kyle', 20, 6.6),
('Laura', 17, 6.4),
('Mike', 19, 7.0),
('Nina', 22, 7.2),
('Oscar', 18, 8.4);

In [14]:
CREATE TABLE matricula (
    id INT PRIMARY KEY AUTO_INCREMENT,
    id_aluno INT REFERENCES aluno(id_aluno),
    nome_da_aula VARCHAR(100)
);

In [15]:
INSERT INTO matricula (id_aluno, nome_da_aula) VALUES
(1, 'Matemática'),
(1, 'História'),
(2, 'Física'),
(2, 'Matemática'),
(3, 'História'),
(3, 'Química'),
(4, 'Matemática'),
(5, 'Física'),
(5, 'História'),
(6, 'Química'),
(7, 'Matemática'),
(8, 'História'),
(8, 'Química'),
(9, 'Física'),
(10, 'História'),
(11, 'Matemática'),
(12, 'Física'),
(12, 'Química'),
(13, 'História'),
(14, 'Física'),
(14, 'Química'),
(15, 'Matemática');

In [16]:
SELECT
    COUNT(*) AS total_alunos,
    AVG(idade) AS media_idade,
    AVG(nota) AS media_nota
FROM aluno;

,total_alunos,media_idade,media_nota
0,90,19.4,7.853333

In [17]:
SELECT
    idade,
    COUNT(*) AS n_alunos_idade,
    AVG(nota) AS media_nota
FROM aluno
GROUP BY idade
ORDER BY idade DESC;

,idade,n_alunos_idade,media_nota
0,22,12,8.150000
1,21,12,6.700000
2,20,18,8.300000
3,19,18,8.766666
4,18,18,8.333333
5,17,12,5.950000

In [18]:
SELECT
    idade,
    COUNT(*) AS n_alunos_idade,
    AVG(nota) AS media_nota
FROM aluno
GROUP BY idade
HAVING COUNT(*) > 2
ORDER BY idade DESC;

,idade,n_alunos_idade,media_nota
0,22,12,8.150000
1,21,12,6.700000
2,20,18,8.300000
3,19,18,8.766666
4,18,18,8.333333
5,17,12,5.950000

In [19]:
SELECT
    nome,
    nota
FROM aluno
WHERE nota < (SELECT AVG(nota) FROM aluno);

,nome,nota
0,Bob,7.4
1,Diana,5.5
2,Edward,7.7
3,Ian,5.7
4,Kyle,6.6
5,Laura,6.4
6,Mike,7.0
7,Nina,7.2
8,Bob,7.4
9,Diana,5.5
10,Edward,7.7
11,Ian,5.7
12,Kyle,6.6
13,Laura,6.4
14,Mike,7.0
15,Nina,7.2
16,Bob,7.4
17,Diana,5.5
18,Edward,7.7
19,Ian,5.7
20,Kyle,6.6
21,Laura,6.4
22,Mike,7.0
23,Nina,7.2
24,Bob,7.4
25,Diana,5.5
26,Edward,7.7
27,Ian,5.7
28,Kyle,6.6
29,Laura,6.4
30,Mike,7.0
31,Nina,7.2
32,Bob,7.4
33,Diana,5.5
34,Edward,7.7
35,Ian,5.7
36,Kyle,6.6
37,Laura,6.4
38,Mike,7.0
39,Nina,7.2
40,Bob,7.4
41,Diana,5.5
42,Edward,7.7
43,Ian,5.7
44,Kyle,6.6
45,Laura,6.4
46,Mike,7.0
47,Nina,7.2

In [20]:
SELECT
    nome,
    idade,
    nota,
    RANK() OVER (
        PARTITION BY idade 
        ORDER BY nota DESC) AS ranque
FROM aluno
ORDER BY idade, nota DESC;

,nome,idade,nota,ranque
0,Laura,17,6.4,1
1,Laura,17,6.4,1
2,Laura,17,6.4,1
3,Laura,17,6.4,1
4,Laura,17,6.4,1
5,Laura,17,6.4,1
6,Diana,17,5.5,7
7,Diana,17,5.5,7
8,Diana,17,5.5,7
9,Diana,17,5.5,7
10,Diana,17,5.5,7
11,Diana,17,5.5,7
12,Julia,18,9.2,1
13,Julia,18,9.2,1
14,Julia,18,9.2,1
15,Julia,18,9.2,1
16,Julia,18,9.2,1
17,Julia,18,9.2,1
18,Oscar,18,8.4,7
19,Oscar,18,8.4,7
20,Oscar,18,8.4,7
21,Oscar,18,8.4,7
22,Oscar,18,8.4,7
23,Oscar,18,8.4,7
24,Bob,18,7.4,13
25,Bob,18,7.4,13
26,Bob,18,7.4,13
27,Bob,18,7.4,13
28,Bob,18,7.4,13
29,Bob,18,7.4,13
30,Fiona,19,9.9,1
31,Fiona,19,9.9,1
32,Fiona,19,9.9,1
33,Fiona,19,9.9,1
34,Fiona,19,9.9,1
35,Fiona,19,9.9,1
36,Hannah,19,9.4,7
37,Hannah,19,9.4,7
38,Hannah,19,9.4,7
39,Hannah,19,9.4,7
40,Hannah,19,9.4,7
41,Hannah,19,9.4,7
42,Mike,19,7.0,13
43,Mike,19,7.0,13
44,Mike,19,7.0,13
45,Mike,19,7.0,13
46,Mike,19,7.0,13
47,Mike,19,7.0,13
48,George,20,9.8,1
49,George,20,9.8,1
50,George,20,9.8,1
51,George,20,9.8,1
52,George,20,9.8,1
53,George,20,9.8,1
54,Alice,20,8.5,7
55,Alice,20,8.5,7
56,Alice,20,8.5,7
57,Alice,20,8.5,7
58,Alice,20,8.5,7
59,Alice,20,8.5,7
60,Kyle,20,6.6,13
61,Kyle,20,6.6,13
62,Kyle,20,6.6,13
63,Kyle,20,6.6,13
64,Kyle,20,6.6,13
65,Kyle,20,6.6,13
66,Edward,21,7.7,1
67,Edward,21,7.7,1
68,Edward,21,7.7,1
69,Edward,21,7.7,1
70,Edward,21,7.7,1
71,Edward,21,7.7,1
72,Ian,21,5.7,7
73,Ian,21,5.7,7
74,Ian,21,5.7,7
75,Ian,21,5.7,7
76,Ian,21,5.7,7
77,Ian,21,5.7,7
78,Charlie,22,9.1,1
79,Charlie,22,9.1,1
80,Charlie,22,9.1,1
81,Charlie,22,9.1,1
82,Charlie,22,9.1,1
83,Charlie,22,9.1,1
84,Nina,22,7.2,7
85,Nina,22,7.2,7
86,Nina,22,7.2,7
87,Nina,22,7.2,7
88,Nina,22,7.2,7
89,Nina,22,7.2,7

In [21]:
SELECT
    nome,
    nota,
    AVG(nota) OVER () AS nota_media
FROM aluno
ORDER BY nota DESC;

,nome,nota,nota_media
0,Fiona,9.9,7.853333
1,Fiona,9.9,7.853333
2,Fiona,9.9,7.853333
3,Fiona,9.9,7.853333
4,Fiona,9.9,7.853333
5,Fiona,9.9,7.853333
6,George,9.8,7.853333
7,George,9.8,7.853333
8,George,9.8,7.853333
9,George,9.8,7.853333
10,George,9.8,7.853333
11,George,9.8,7.853333
12,Hannah,9.4,7.853333
13,Hannah,9.4,7.853333
14,Hannah,9.4,7.853333
15,Hannah,9.4,7.853333
16,Hannah,9.4,7.853333
17,Hannah,9.4,7.853333
18,Julia,9.2,7.853333
19,Julia,9.2,7.853333
20,Julia,9.2,7.853333
21,Julia,9.2,7.853333
22,Julia,9.2,7.853333
23,Julia,9.2,7.853333
24,Charlie,9.1,7.853333
25,Charlie,9.1,7.853333
26,Charlie,9.1,7.853333
27,Charlie,9.1,7.853333
28,Charlie,9.1,7.853333
29,Charlie,9.1,7.853333
30,Alice,8.5,7.853333
31,Alice,8.5,7.853333
32,Alice,8.5,7.853333
33,Alice,8.5,7.853333
34,Alice,8.5,7.853333
35,Alice,8.5,7.853333
36,Oscar,8.4,7.853333
37,Oscar,8.4,7.853333
38,Oscar,8.4,7.853333
39,Oscar,8.4,7.853333
40,Oscar,8.4,7.853333
41,Oscar,8.4,7.853333
42,Edward,7.7,7.853333
43,Edward,7.7,7.853333
44,Edward,7.7,7.853333
45,Edward,7.7,7.853333
46,Edward,7.7,7.853333
47,Edward,7.7,7.853333
48,Bob,7.4,7.853333
49,Bob,7.4,7.853333
50,Bob,7.4,7.853333
51,Bob,7.4,7.853333
52,Bob,7.4,7.853333
53,Bob,7.4,7.853333
54,Nina,7.2,7.853333
55,Nina,7.2,7.853333
56,Nina,7.2,7.853333
57,Nina,7.2,7.853333
58,Nina,7.2,7.853333
59,Nina,7.2,7.853333
60,Mike,7.0,7.853333
61,Mike,7.0,7.853333
62,Mike,7.0,7.853333
63,Mike,7.0,7.853333
64,Mike,7.0,7.853333
65,Mike,7.0,7.853333
66,Kyle,6.6,7.853333
67,Kyle,6.6,7.853333
68,Kyle,6.6,7.853333
69,Kyle,6.6,7.853333
70,Kyle,6.6,7.853333
71,Kyle,6.6,7.853333
72,Laura,6.4,7.853333
73,Laura,6.4,7.853333
74,Laura,6.4,7.853333
75,Laura,6.4,7.853333
76,Laura,6.4,7.853333
77,Laura,6.4,7.853333
78,Ian,5.7,7.853333
79,Ian,5.7,7.853333
80,Ian,5.7,7.853333
81,Ian,5.7,7.853333
82,Ian,5.7,7.853333
83,Ian,5.7,7.853333
84,Diana,5.5,7.853333
85,Diana,5.5,7.853333
86,Diana,5.5,7.853333
87,Diana,5.5,7.853333
88,Diana,5.5,7.853333
89,Diana,5.5,7.853333

In [22]:
SELECT
    nome,
    idade,
    nota,
    AVG(nota) OVER (PARTITION BY idade) AS nota_media
FROM aluno
ORDER BY nota DESC;

,nome,idade,nota,nota_media
0,Fiona,19,9.9,8.766666
1,Fiona,19,9.9,8.766666
2,Fiona,19,9.9,8.766666
3,Fiona,19,9.9,8.766666
4,Fiona,19,9.9,8.766666
5,Fiona,19,9.9,8.766666
6,George,20,9.8,8.300000
7,George,20,9.8,8.300000
8,George,20,9.8,8.300000
9,George,20,9.8,8.300000
10,George,20,9.8,8.300000
11,George,20,9.8,8.300000
12,Hannah,19,9.4,8.766666
13,Hannah,19,9.4,8.766666
14,Hannah,19,9.4,8.766666
15,Hannah,19,9.4,8.766666
16,Hannah,19,9.4,8.766666
17,Hannah,19,9.4,8.766666
18,Julia,18,9.2,8.333333
19,Julia,18,9.2,8.333333
20,Julia,18,9.2,8.333333
21,Julia,18,9.2,8.333333
22,Julia,18,9.2,8.333333
23,Julia,18,9.2,8.333333
24,Charlie,22,9.1,8.150000
25,Charlie,22,9.1,8.150000
26,Charlie,22,9.1,8.150000
27,Charlie,22,9.1,8.150000
28,Charlie,22,9.1,8.150000
29,Charlie,22,9.1,8.150000
30,Alice,20,8.5,8.300000
31,Alice,20,8.5,8.300000
32,Alice,20,8.5,8.300000
33,Alice,20,8.5,8.300000
34,Alice,20,8.5,8.300000
35,Alice,20,8.5,8.300000
36,Oscar,18,8.4,8.333333
37,Oscar,18,8.4,8.333333
38,Oscar,18,8.4,8.333333
39,Oscar,18,8.4,8.333333
40,Oscar,18,8.4,8.333333
41,Oscar,18,8.4,8.333333
42,Edward,21,7.7,6.700000
43,Edward,21,7.7,6.700000
44,Edward,21,7.7,6.700000
45,Edward,21,7.7,6.700000
46,Edward,21,7.7,6.700000
47,Edward,21,7.7,6.700000
48,Bob,18,7.4,8.333333
49,Bob,18,7.4,8.333333
50,Bob,18,7.4,8.333333
51,Bob,18,7.4,8.333333
52,Bob,18,7.4,8.333333
53,Bob,18,7.4,8.333333
54,Nina,22,7.2,8.150000
55,Nina,22,7.2,8.150000
56,Nina,22,7.2,8.150000
57,Nina,22,7.2,8.150000
58,Nina,22,7.2,8.150000
59,Nina,22,7.2,8.150000
60,Mike,19,7.0,8.766666
61,Mike,19,7.0,8.766666
62,Mike,19,7.0,8.766666
63,Mike,19,7.0,8.766666
64,Mike,19,7.0,8.766666
65,Mike,19,7.0,8.766666
66,Kyle,20,6.6,8.300000
67,Kyle,20,6.6,8.300000
68,Kyle,20,6.6,8.300000
69,Kyle,20,6.6,8.300000
70,Kyle,20,6.6,8.300000
71,Kyle,20,6.6,8.300000
72,Laura,17,6.4,5.950000
73,Laura,17,6.4,5.950000
74,Laura,17,6.4,5.950000
75,Laura,17,6.4,5.950000
76,Laura,17,6.4,5.950000
77,Laura,17,6.4,5.950000
78,Ian,21,5.7,6.700000
79,Ian,21,5.7,6.700000
80,Ian,21,5.7,6.700000
81,Ian,21,5.7,6.700000
82,Ian,21,5.7,6.700000
83,Ian,21,5.7,6.700000
84,Diana,17,5.5,5.950000
85,Diana,17,5.5,5.950000
86,Diana,17,5.5,5.950000
87,Diana,17,5.5,5.950000
88,Diana,17,5.5,5.950000
89,Diana,17,5.5,5.950000

In [23]:
SELECT
    nome,
    nota,
    (
SELECT AVG(nota)
     FROM aluno
) AS media_nota
FROM aluno
WHERE nota > (
    SELECT AVG(nota)
    FROM aluno
);

,nome,nota,media_nota
0,Alice,8.5,7.853333
1,Charlie,9.1,7.853333
2,Fiona,9.9,7.853333
3,George,9.8,7.853333
4,Hannah,9.4,7.853333
5,Julia,9.2,7.853333
6,Oscar,8.4,7.853333
7,Alice,8.5,7.853333
8,Charlie,9.1,7.853333
9,Fiona,9.9,7.853333
10,George,9.8,7.853333
11,Hannah,9.4,7.853333
12,Julia,9.2,7.853333
13,Oscar,8.4,7.853333
14,Alice,8.5,7.853333
15,Charlie,9.1,7.853333
16,Fiona,9.9,7.853333
17,George,9.8,7.853333
18,Hannah,9.4,7.853333
19,Julia,9.2,7.853333
20,Oscar,8.4,7.853333
21,Alice,8.5,7.853333
22,Charlie,9.1,7.853333
23,Fiona,9.9,7.853333
24,George,9.8,7.853333
25,Hannah,9.4,7.853333
26,Julia,9.2,7.853333
27,Oscar,8.4,7.853333
28,Alice,8.5,7.853333
29,Charlie,9.1,7.853333
30,Fiona,9.9,7.853333
31,George,9.8,7.853333
32,Hannah,9.4,7.853333
33,Julia,9.2,7.853333
34,Oscar,8.4,7.853333
35,Alice,8.5,7.853333
36,Charlie,9.1,7.853333
37,Fiona,9.9,7.853333
38,George,9.8,7.853333
39,Hannah,9.4,7.853333
40,Julia,9.2,7.853333
41,Oscar,8.4,7.853333

In [24]:
WITH aluno_media_geral AS (
SELECT
    nome,
    nota,
    AVG(nota) OVER () AS media_geral
FROM aluno
)
SELECT *
FROM aluno_media_geral
WHERE nota > media_geral;

,nome,nota,media_geral
0,Alice,8.5,7.853333
1,Charlie,9.1,7.853333
2,Fiona,9.9,7.853333
3,George,9.8,7.853333
4,Hannah,9.4,7.853333
5,Julia,9.2,7.853333
6,Oscar,8.4,7.853333
7,Alice,8.5,7.853333
8,Charlie,9.1,7.853333
9,Fiona,9.9,7.853333
10,George,9.8,7.853333
11,Hannah,9.4,7.853333
12,Julia,9.2,7.853333
13,Oscar,8.4,7.853333
14,Alice,8.5,7.853333
15,Charlie,9.1,7.853333
16,Fiona,9.9,7.853333
17,George,9.8,7.853333
18,Hannah,9.4,7.853333
19,Julia,9.2,7.853333
20,Oscar,8.4,7.853333
21,Alice,8.5,7.853333
22,Charlie,9.1,7.853333
23,Fiona,9.9,7.853333
24,George,9.8,7.853333
25,Hannah,9.4,7.853333
26,Julia,9.2,7.853333
27,Oscar,8.4,7.853333
28,Alice,8.5,7.853333
29,Charlie,9.1,7.853333
30,Fiona,9.9,7.853333
31,George,9.8,7.853333
32,Hannah,9.4,7.853333
33,Julia,9.2,7.853333
34,Oscar,8.4,7.853333
35,Alice,8.5,7.853333
36,Charlie,9.1,7.853333
37,Fiona,9.9,7.853333
38,George,9.8,7.853333
39,Hannah,9.4,7.853333
40,Julia,9.2,7.853333
41,Oscar,8.4,7.853333

In [25]:
SELECT
    nome,
    nota,
    CASE
        WHEN nota >= 6 THEN 'Aprovado'
        ELSE 'Reprovado'
    END AS status
FROM aluno;

,nome,nota,status
0,Alice,8.5,Aprovado
1,Bob,7.4,Aprovado
2,Charlie,9.1,Aprovado
3,Diana,5.5,Reprovado
4,Edward,7.7,Aprovado
5,Fiona,9.9,Aprovado
6,George,9.8,Aprovado
7,Hannah,9.4,Aprovado
8,Ian,5.7,Reprovado
9,Julia,9.2,Aprovado
10,Kyle,6.6,Aprovado
11,Laura,6.4,Aprovado
12,Mike,7.0,Aprovado
13,Nina,7.2,Aprovado
14,Oscar,8.4,Aprovado
15,Alice,8.5,Aprovado
16,Bob,7.4,Aprovado
17,Charlie,9.1,Aprovado
18,Diana,5.5,Reprovado
19,Edward,7.7,Aprovado
20,Fiona,9.9,Aprovado
21,George,9.8,Aprovado
22,Hannah,9.4,Aprovado
23,Ian,5.7,Reprovado
24,Julia,9.2,Aprovado
25,Kyle,6.6,Aprovado
26,Laura,6.4,Aprovado
27,Mike,7.0,Aprovado
28,Nina,7.2,Aprovado
29,Oscar,8.4,Aprovado
30,Alice,8.5,Aprovado
31,Bob,7.4,Aprovado
32,Charlie,9.1,Aprovado
33,Diana,5.5,Reprovado
34,Edward,7.7,Aprovado
35,Fiona,9.9,Aprovado
36,George,9.8,Aprovado
37,Hannah,9.4,Aprovado
38,Ian,5.7,Reprovado
39,Julia,9.2,Aprovado
40,Kyle,6.6,Aprovado
41,Laura,6.4,Aprovado
42,Mike,7.0,Aprovado
43,Nina,7.2,Aprovado
44,Oscar,8.4,Aprovado
45,Alice,8.5,Aprovado
46,Bob,7.4,Aprovado
47,Charlie,9.1,Aprovado
48,Diana,5.5,Reprovado
49,Edward,7.7,Aprovado
50,Fiona,9.9,Aprovado
51,George,9.8,Aprovado
52,Hannah,9.4,Aprovado
53,Ian,5.7,Reprovado
54,Julia,9.2,Aprovado
55,Kyle,6.6,Aprovado
56,Laura,6.4,Aprovado
57,Mike,7.0,Aprovado
58,Nina,7.2,Aprovado
59,Oscar,8.4,Aprovado
60,Alice,8.5,Aprovado
61,Bob,7.4,Aprovado
62,Charlie,9.1,Aprovado
63,Diana,5.5,Reprovado
64,Edward,7.7,Aprovado
65,Fiona,9.9,Aprovado
66,George,9.8,Aprovado
67,Hannah,9.4,Aprovado
68,Ian,5.7,Reprovado
69,Julia,9.2,Aprovado
70,Kyle,6.6,Aprovado
71,Laura,6.4,Aprovado
72,Mike,7.0,Aprovado
73,Nina,7.2,Aprovado
74,Oscar,8.4,Aprovado
75,Alice,8.5,Aprovado
76,Bob,7.4,Aprovado
77,Charlie,9.1,Aprovado
78,Diana,5.5,Reprovado
79,Edward,7.7,Aprovado
80,Fiona,9.9,Aprovado
81,George,9.8,Aprovado
82,Hannah,9.4,Aprovado
83,Ian,5.7,Reprovado
84,Julia,9.2,Aprovado
85,Kyle,6.6,Aprovado
86,Laura,6.4,Aprovado
87,Mike,7.0,Aprovado
88,Nina,7.2,Aprovado
89,Oscar,8.4,Aprovado